# для подключение mysql
#version: '3.7'
#services:
#  mysql:
#    image: mysql:8.0
#    restart: always
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_DATABASE=app
#      - MYSQL_USER=app
#      - MYSQL_PASSWORD=pass

# для подключение postgresql
version: '3.1'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass